---
  swagger: "2.0"
  info:
    title: "Todoist Sample Application"
    description: "A web app to manage a todo list."
    contact:
      name: "AOE GmbH"
      url: "https://www.aoe.com"
    version: "1.0.0"
  consumes:
    - application/json
  produces:
    - application/json